image: python:3.8
variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - test
  - pre-publish
  - publish

test:lint:
  stage: test
  script:
    - pip install tox
    - make lint

test:format:
  stage: test
  script:
    - pip install tox
    - make format-check

publish_package:staging:
  stage: pre-publish
  only:
    - /^release/.*$/
  variables:
    TWINE_USERNAME: $PYPI_STAGING_USERNAME
    TWINE_PASSWORD: $PYPI_STAGING_PASSWORD
  script:
    - pip install tox
    - make pypi-check
    - make pypi-upload OPTIONS="-- --repository-url https://test.pypi.org/legacy/"

publish-package:production:
  stage: publish
  only:
    - /^release/.*$/
  variables:
    TWINE_USERNAME: $PYPI_PRODUCTION_USERNAME
    TWINE_PASSWORD: $PYPI_PRODUCTION_PASSWORD
  script:
    - pip install tox
    - make pypi-check
    - make pypi-upload

publish-docker:
  stage: publish
  image: docker
  only:
    - master
  before_script:
    - apk add python3-dev python3-setuptools
    - python3 setup.py sdist
  script:
    - export VERSION_TAG=$(cat setup.py | grep version | head -1 | awk -F= '{ print $2 }' | sed 's/[",]//g' | tr -d "'")
    - docker login ${CI_REGISTRY} -u gitlab-ci-token -p ${CI_BUILD_TOKEN}
    - docker build -t ${CI_REGISTRY_IMAGE}:latest -t ${CI_REGISTRY_IMAGE}:${VERSION_TAG}  .
    - docker push ${CI_REGISTRY_IMAGE}:latest
    - docker push ${CI_REGISTRY_IMAGE}:${VERSION_TAG}
    - docker login -u hmajid2301 -p ${DOCKER_PASSWORD}
    - export IMAGE_NAME="hmajid2301/gitlab-github-mirror-repo"
    - docker build -t ${IMAGE_NAME}:latest -t ${IMAGE_NAME}:${VERSION_TAG}  .
    - docker push ${IMAGE_NAME}:latest
    - docker push ${IMAGE_NAME}:${VERSION_TAG}

publish-readme:hub:
  stage: publish
  only:
    - master
  image:
    name: registry.gitlab.com/hmajid2301/dockerhub-descriptions-updater
    entrypoint: [""]
  variables:
    DOCKERHUB_USERNAME: hmajid2301
    DOCKERHUB_PASSWORD: ${DOCKER_PASSWORD}
    DOCKERHUB_REPO_NAME: markdown-mermaid-to-images
  script:
    - pandoc --from rst README.rst --to markdown_strict -o README.md
    - node /app/index.js
